name: dart_web_app
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.5
  rpc: ^0.6.0
  http: ^0.11.1
  safe_config: ^2.0.2
dev_dependencies:
  pedantic: ^1.8.0
